### ISSUE TITLE
PlaceholderAPI tags are not recognized unless leading space is present.

### ISSUE THREAD

**Issue by astridos2go** [rogi27/RenameIt#3]
I'm using this mod on a Fabric 1.19 server, and I realized that I am having an issue where the `/renameit` command will not recognize ANY formatting in my new tool name, unless I leave a leading space at the beginning of the string. Obviously this isn't too much of an issue, but it is very annoying.

**Comment by 27rogi** [comment]
Weird. Might be something with the library. Will look into it.

**Comment by NDsystem-666** [comment]
found a workaround: by adding a leading empty tag like `<red></red>` you an get rid of the leading space

**Comment by astridos2go** [comment]
Hi, any update on this issue? The workaround with the empty tag does solve my leading space issue, but it would be nice if it was resolved entirely.

Of course, I understand you're a human being and surely have other better things to do other than work on this mod full time, so I am more than willing to try and help, although my modding experience is virtually non-existent. Let me know if there's anything you want me to do! Other than that, there is absolutely no rush. 

Thank you again!

**Comment by 27rogi** [comment]
Currently I am dealing with the problems of Fabric2Discord, but I will prioritize this one.

**Comment by 27rogi** [comment]
should be fixed in new version
