### ISSUE TITLE
quotation marks from /ri name "..." in item-names

### ISSUE THREAD

**Issue by NDsystem-666** [rogi27/RenameIt#4]
After the 1.3.0 Update, there is a new issue with renaming: if i use `/ri name "cool <red>name</red>"` the item will have the quotation marks in the name regardless of the placement of any tags

**Comment by 27rogi** [comment]
Due to changes to command arguments in 1.3.0 you are no longer required to wrap string in quotation marks, but looks like I forgot to change suggestions for commands, this will be fixed in future update.
