### ISSUE TITLE
I'd love to see this mod on 1.20

### ISSUE THREAD

**Issue by glxy14colourse** [rogi27/RenameIt#7]
This is a great mod

**Comment by 27rogi** [comment]
I'm currently working on a mod that includes all functionality from this one, should be done before end of this month.

**Comment by Riyuukii** [comment]
is the 1.20 version out yet?

**Comment by 27rogi** [comment]
> is the 1.20 version out yet?

Hi, functionality from this mod is now implemented as a part of Server Toolbox mod, you can check it here: https://modrinth.com/mod/server-toolbox-fabric

**Comment by DraconicVelum** [comment]
> > is the 1.20 version out yet?
> 
> Hi, functionality from this mod is now implemented as a part of Server Toolbox mod, you can check it here: https://modrinth.com/mod/server-toolbox-fabric

Sad, i would like to use only on client side

**Comment by 27rogi** [comment]
> Sad, i would like to use only on client side

This mod should work on client side too, because singleplayer and multiplayer utilizes almost same API.
